-- Meal Prep & Nutrition Planner
-- Supabase PostgreSQL schema. Run after enabling the pgcrypto extension.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  sex text check (sex in ('male', 'female')),
  age integer check (age between 14 and 100),
  height_cm numeric(5, 1) check (height_cm between 100 and 250),
  weight_kg numeric(5, 1) check (weight_kg between 25 and 300),
  activity_factor numeric(4, 3) check (activity_factor in (1.200, 1.375, 1.550)),
  goal text check (goal in ('cut', 'maintain', 'bulk')),
  target_kcal numeric(7, 1) check (target_kcal > 0),
  protein_g numeric(6, 1) check (protein_g >= 0),
  carbs_g numeric(6, 1) check (carbs_g >= 0),
  fat_g numeric(6, 1) check (fat_g >= 0),
  baseline_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null check (category in ('肉禽', '水产', '蛋奶', '蔬菜', '水果', '碳水', '调料', '其他')),
  kcal_per_100g numeric(7, 2) not null check (kcal_per_100g >= 0),
  protein_per_100g numeric(6, 2) not null check (protein_per_100g >= 0),
  carbs_per_100g numeric(6, 2) not null check (carbs_per_100g >= 0),
  fat_per_100g numeric(6, 2) not null check (fat_per_100g >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  description text,
  servings numeric(6, 2) not null default 1 check (servings > 0),
  total_kcal numeric(8, 1) not null default 0 check (total_kcal >= 0),
  total_protein_g numeric(7, 1) not null default 0 check (total_protein_g >= 0),
  total_carbs_g numeric(7, 1) not null default 0 check (total_carbs_g >= 0),
  total_fat_g numeric(7, 1) not null default 0 check (total_fat_g >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_ingredients (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  raw_weight_g numeric(8, 1) not null check (raw_weight_g > 0),
  primary key (recipe_id, ingredient_id)
);

create table if not exists public.meal_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  meal_count integer not null default 5 check (meal_count between 1 and 21),
  status text not null default 'draft' check (status in ('draft', 'confirmed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start)
);

create table if not exists public.meal_plan_items (
  id uuid primary key default gen_random_uuid(),
  meal_plan_id uuid not null references public.meal_plans(id) on delete cascade,
  recipe_id uuid not null references public.recipes(id) on delete restrict,
  planned_date date not null,
  servings numeric(6, 2) not null default 1 check (servings > 0),
  created_at timestamptz not null default now(),
  unique (meal_plan_id, planned_date, recipe_id)
);

create index if not exists recipes_user_id_idx on public.recipes(user_id);
create index if not exists recipe_ingredients_ingredient_id_idx on public.recipe_ingredients(ingredient_id);
create index if not exists meal_plans_user_week_idx on public.meal_plans(user_id, week_start);
create index if not exists meal_plan_items_plan_date_idx on public.meal_plan_items(meal_plan_id, planned_date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists recipes_set_updated_at on public.recipes;
create trigger recipes_set_updated_at before update on public.recipes
for each row execute function public.set_updated_at();

drop trigger if exists meal_plans_set_updated_at on public.meal_plans;
create trigger meal_plans_set_updated_at before update on public.meal_plans
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.meal_plans enable row level security;
alter table public.meal_plan_items enable row level security;

drop policy if exists profiles_owner_all on public.profiles;
create policy profiles_owner_all on public.profiles for all
using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists ingredients_authenticated_read on public.ingredients;
create policy ingredients_authenticated_read on public.ingredients for select
to authenticated using (is_active = true);

drop policy if exists recipes_owner_all on public.recipes;
create policy recipes_owner_all on public.recipes for all
using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists recipe_ingredients_owner_all on public.recipe_ingredients;
create policy recipe_ingredients_owner_all on public.recipe_ingredients for all
using (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
))
with check (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));

drop policy if exists meal_plans_owner_all on public.meal_plans;
create policy meal_plans_owner_all on public.meal_plans for all
using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists meal_plan_items_owner_all on public.meal_plan_items;
create policy meal_plan_items_owner_all on public.meal_plan_items for all
using (exists (
  select 1 from public.meal_plans p
  where p.id = meal_plan_id and p.user_id = auth.uid()
)
and exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
))
with check (exists (
  select 1 from public.meal_plans p
  where p.id = meal_plan_id and p.user_id = auth.uid()
)
and exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));
