-- Meal Prep & Nutrition Planner
-- Supabase PostgreSQL schema.
-- Run this file before supabase/seed.sql.

create extension if not exists pgcrypto;

-- A profile mirrors auth.users and stores the user's current nutrition baseline.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  sex text check (sex in ('male', 'female')),
  age integer check (age between 14 and 100),
  height_cm numeric(5, 1) check (height_cm between 100 and 250),
  weight_kg numeric(5, 1) check (weight_kg between 25 and 300),
  activity_factor numeric(4, 3) check (activity_factor in (1.200, 1.375, 1.550)),
  goal text check (goal in ('cut', 'maintain', 'bulk')),
  target_kcal numeric(7, 1) check (target_kcal > 0),
  protein_g numeric(6, 1) check (protein_g >= 0),
  carbs_g numeric(6, 1) check (carbs_g >= 0),
  fat_g numeric(6, 1) check (fat_g >= 0),
  baseline_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Nutrition values are raw-food values per 100g. Category values are stable
-- codes; the API/UI owns their localized display names.
create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null check (category in (
    'meat', 'seafood', 'dairy', 'vegetable', 'fruit', 'carb', 'seasoning', 'other'
  )),
  nutrition_basis text not null default 'raw' check (nutrition_basis = 'raw'),
  kcal_per_100g numeric(7, 2) not null check (kcal_per_100g >= 0),
  protein_per_100g numeric(6, 2) not null check (protein_per_100g >= 0),
  carbs_per_100g numeric(6, 2) not null check (carbs_per_100g >= 0),
  fat_per_100g numeric(6, 2) not null check (fat_per_100g >= 0),
  data_source text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- A recipe is one directly consumable plate. It is not a batch/casserole
-- entity and therefore intentionally has no servings/yield fields.
create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  description text,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_ingredients (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete restrict,
  raw_weight_g numeric(8, 1) not null check (raw_weight_g > 0),
  primary key (recipe_id, ingredient_id)
);

-- The target values are a snapshot captured when the plan is created. They
-- must not change when the profile's current baseline is edited later.
create table if not exists public.meal_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  status text not null default 'draft' check (status in ('draft', 'confirmed')),
  target_kcal numeric(7, 1) not null check (target_kcal > 0),
  target_protein_g numeric(6, 1) not null check (target_protein_g >= 0),
  target_carbs_g numeric(6, 1) not null check (target_carbs_g >= 0),
  target_fat_g numeric(6, 1) not null check (target_fat_g >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start),
  check (extract(isodow from week_start) = 1)
);

create table if not exists public.meal_plan_items (
  id uuid primary key default gen_random_uuid(),
  meal_plan_id uuid not null references public.meal_plans(id) on delete cascade,
  planned_date date not null,
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner')),
  input_mode text not null check (input_mode in ('recipe', 'manual')),
  recipe_id uuid references public.recipes(id) on delete restrict,
  meal_name text check (meal_name is null or char_length(meal_name) between 1 and 80),
  quantity numeric(6, 2),
  manual_kcal numeric(8, 1) check (manual_kcal >= 0),
  manual_protein_g numeric(7, 1) check (manual_protein_g >= 0),
  manual_carbs_g numeric(7, 1) check (manual_carbs_g >= 0),
  manual_fat_g numeric(7, 1) check (manual_fat_g >= 0),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  check (
    (
      input_mode = 'recipe'
      and recipe_id is not null
      and quantity is not null
      and quantity > 0
      and manual_kcal is null
      and manual_protein_g is null
      and manual_carbs_g is null
      and manual_fat_g is null
    )
    or
    (
      input_mode = 'manual'
      and recipe_id is null
      and quantity is null
      and manual_kcal is not null
      and manual_protein_g is not null
      and manual_carbs_g is not null
      and manual_fat_g is not null
    )
  )
);

create index if not exists recipes_user_id_idx on public.recipes(user_id);
create index if not exists recipes_active_user_idx
  on public.recipes(user_id, archived_at);
create index if not exists recipe_ingredients_ingredient_id_idx
  on public.recipe_ingredients(ingredient_id);
create index if not exists meal_plans_user_week_idx
  on public.meal_plans(user_id, week_start);
create index if not exists meal_plan_items_plan_date_idx
  on public.meal_plan_items(meal_plan_id, planned_date, meal_type);
create index if not exists meal_plan_items_recipe_idx
  on public.meal_plan_items(recipe_id)
  where recipe_id is not null;

-- Nutrition is always derived from ingredient detail. These views deliberately
-- do not read client-provided totals.
create or replace view public.recipe_nutrition
with (security_invoker = true)
as
select
  r.id as recipe_id,
  r.user_id,
  count(ri.ingredient_id)::integer as ingredient_count,
  coalesce(sum(i.kcal_per_100g * ri.raw_weight_g / 100), 0)::numeric(12, 1)
    as total_kcal,
  coalesce(sum(i.protein_per_100g * ri.raw_weight_g / 100), 0)::numeric(10, 1)
    as total_protein_g,
  coalesce(sum(i.carbs_per_100g * ri.raw_weight_g / 100), 0)::numeric(10, 1)
    as total_carbs_g,
  coalesce(sum(i.fat_per_100g * ri.raw_weight_g / 100), 0)::numeric(10, 1)
    as total_fat_g
from public.recipes r
left join public.recipe_ingredients ri on ri.recipe_id = r.id
left join public.ingredients i on i.id = ri.ingredient_id
group by r.id, r.user_id;

create or replace view public.meal_plan_item_nutrition
with (security_invoker = true)
as
select
  mpi.id as meal_plan_item_id,
  mpi.meal_plan_id,
  mpi.planned_date,
  mpi.meal_type,
  mpi.input_mode,
  mpi.recipe_id,
  coalesce(mpi.meal_name, r.name) as meal_name,
  mpi.quantity,
  case
    when mpi.input_mode = 'recipe' then rn.total_kcal * mpi.quantity
    else mpi.manual_kcal
  end::numeric(12, 1) as total_kcal,
  case
    when mpi.input_mode = 'recipe' then rn.total_protein_g * mpi.quantity
    else mpi.manual_protein_g
  end::numeric(10, 1) as total_protein_g,
  case
    when mpi.input_mode = 'recipe' then rn.total_carbs_g * mpi.quantity
    else mpi.manual_carbs_g
  end::numeric(10, 1) as total_carbs_g,
  case
    when mpi.input_mode = 'recipe' then rn.total_fat_g * mpi.quantity
    else mpi.manual_fat_g
  end::numeric(10, 1) as total_fat_g
from public.meal_plan_items mpi
left join public.recipes r on r.id = mpi.recipe_id
left join public.recipe_nutrition rn on rn.recipe_id = mpi.recipe_id;

-- One row per calendar day and meal type. Multiple dishes in the same meal
-- are intentionally aggregated here rather than constrained at write time.
create or replace view public.meal_plan_nutrition
with (security_invoker = true)
as
select
  meal_plan_id,
  planned_date,
  meal_type,
  sum(total_kcal)::numeric(12, 1) as total_kcal,
  sum(total_protein_g)::numeric(10, 1) as total_protein_g,
  sum(total_carbs_g)::numeric(10, 1) as total_carbs_g,
  sum(total_fat_g)::numeric(10, 1) as total_fat_g,
  count(*)::integer as item_count
from public.meal_plan_item_nutrition
group by meal_plan_id, planned_date, meal_type;

create or replace view public.meal_plan_totals
with (security_invoker = true)
as
select
  p.id as meal_plan_id,
  p.user_id,
  p.week_start,
  p.target_kcal,
  p.target_protein_g,
  p.target_carbs_g,
  p.target_fat_g,
  coalesce(sum(n.total_kcal), 0)::numeric(12, 1) as planned_kcal,
  coalesce(sum(n.total_protein_g), 0)::numeric(10, 1) as planned_protein_g,
  coalesce(sum(n.total_carbs_g), 0)::numeric(10, 1) as planned_carbs_g,
  coalesce(sum(n.total_fat_g), 0)::numeric(10, 1) as planned_fat_g,
  count(n.meal_plan_item_id)::integer as planned_item_count
from public.meal_plans p
left join public.meal_plan_item_nutrition n on n.meal_plan_id = p.id
group by
  p.id,
  p.user_id,
  p.week_start,
  p.target_kcal,
  p.target_protein_g,
  p.target_carbs_g,
  p.target_fat_g;

-- Manual meals have no ingredient quantities and are intentionally excluded.
create or replace view public.shopping_list_items
with (security_invoker = true)
as
select
  mpi.meal_plan_id,
  i.id as ingredient_id,
  i.name as ingredient_name,
  i.category,
  sum(ri.raw_weight_g * mpi.quantity)::numeric(12, 1) as total_raw_weight_g
from public.meal_plan_items mpi
join public.recipe_ingredients ri on ri.recipe_id = mpi.recipe_id
join public.ingredients i on i.id = ri.ingredient_id
where mpi.input_mode = 'recipe'
group by mpi.meal_plan_id, i.id, i.name, i.category;

-- Keep mutable aggregate roots' timestamps database-owned.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- All Auth methods share auth.users.id; no credential data is copied.
-- Only optional display text is accepted from user-editable metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    case when jsonb_typeof(new.raw_user_meta_data -> 'display_name') = 'string'
      then nullif(btrim(new.raw_user_meta_data ->> 'display_name'), '')
      else null end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- A recipe and its ingredients are normally written in one transaction. A
-- deferred constraint trigger allows that transaction while preventing empty
-- recipes from being committed.
create or replace function public.assert_recipe_has_ingredients()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (select 1 from public.recipes r where r.id = new.id)
  and not exists (
    select 1
    from public.recipe_ingredients ri
    where ri.recipe_id = new.id
  ) then
    raise exception using
      errcode = '23514',
      message = 'recipe must contain at least one ingredient';
  end if;
  return null;
end;
$$;

create or replace function public.assert_recipe_ingredient_parent()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  recipe_uuid uuid;
  recipe_ids uuid[];
begin
  if tg_op = 'INSERT' then
    recipe_ids := array[new.recipe_id];
  elsif tg_op = 'DELETE' then
    recipe_ids := array[old.recipe_id];
  else
    recipe_ids := array[old.recipe_id, new.recipe_id];
  end if;
  foreach recipe_uuid in array recipe_ids loop
    -- Deleted parents (including account cascades) need no ingredients.
    -- Reassignment must validate both the old and the new surviving parent.
    if exists (select 1 from public.recipes r where r.id = recipe_uuid)
    and not exists (
      select 1 from public.recipe_ingredients ri where ri.recipe_id = recipe_uuid
    ) then
      raise exception using
        errcode = '23514',
        message = 'recipe must contain at least one ingredient';
    end if;
  end loop;
  return null;
end;
$$;

-- Parent edits must preserve the date rule enforced when items are written.
create or replace function public.validate_meal_plan_week()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.week_start is distinct from old.week_start and exists (
    select 1 from public.meal_plan_items mpi
    where mpi.meal_plan_id = old.id
      and (mpi.planned_date < new.week_start or mpi.planned_date > new.week_start + 6)
  ) then
    raise exception using
      errcode = '23514',
      message = 'existing meal items must remain within the plan week';
  end if;
  return new;
end;
$$;

-- Cross-row rules cannot be represented by CHECK constraints.
create or replace function public.validate_meal_plan_item()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  plan_owner uuid;
  plan_week_start date;
  recipe_owner uuid;
  recipe_archived_at timestamptz;
begin
  select p.user_id, p.week_start
    into plan_owner, plan_week_start
  from public.meal_plans p
  where p.id = new.meal_plan_id;

  if plan_owner is null then
    raise exception using
      errcode = '23503',
      message = 'meal plan does not exist';
  end if;

  if new.planned_date < plan_week_start
     or new.planned_date > plan_week_start + 6 then
    raise exception using
      errcode = '23514',
      message = 'planned date must be within the plan week';
  end if;

  if new.input_mode = 'recipe' then
    select r.user_id, r.archived_at
      into recipe_owner, recipe_archived_at
    from public.recipes r
    where r.id = new.recipe_id;

    if recipe_owner is null then
      raise exception using
        errcode = '23503',
        message = 'recipe does not exist';
    end if;

    if recipe_owner is distinct from plan_owner then
      raise exception using
        errcode = '42501',
        message = 'recipe and meal plan must belong to the same user';
    end if;

    if recipe_archived_at is not null then
      raise exception using
        errcode = '23514',
        message = 'archived recipes cannot be added to new plan items';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Existing Auth accounts may predate this trigger. Never overwrite a baseline
-- or a display name already edited in profiles when reapplying the schema.
insert into public.profiles (id, display_name)
select u.id,
  case when jsonb_typeof(u.raw_user_meta_data -> 'display_name') = 'string'
    then nullif(btrim(u.raw_user_meta_data ->> 'display_name'), '')
    else null end
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id)
on conflict (id) do nothing;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists recipes_set_updated_at on public.recipes;
create trigger recipes_set_updated_at
  before update on public.recipes
  for each row execute function public.set_updated_at();

drop trigger if exists meal_plans_set_updated_at on public.meal_plans;
create trigger meal_plans_set_updated_at
  before update on public.meal_plans
  for each row execute function public.set_updated_at();

drop trigger if exists recipes_require_ingredients on public.recipes;
create constraint trigger recipes_require_ingredients
  after insert or update on public.recipes
  deferrable initially deferred
  for each row execute function public.assert_recipe_has_ingredients();

drop trigger if exists recipe_ingredients_require_parent on public.recipe_ingredients;
create constraint trigger recipe_ingredients_require_parent
  after insert or update or delete on public.recipe_ingredients
  deferrable initially deferred
  for each row execute function public.assert_recipe_ingredient_parent();

drop trigger if exists meal_plan_items_validate on public.meal_plan_items;
drop trigger if exists meal_plans_validate_week on public.meal_plans;
create trigger meal_plans_validate_week
  before update of week_start on public.meal_plans
  for each row execute function public.validate_meal_plan_week();

create trigger meal_plan_items_validate
  before insert or update on public.meal_plan_items
  for each row execute function public.validate_meal_plan_item();

-- Row-level security is enabled on every persisted application table.
alter table public.profiles enable row level security;
alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.meal_plans enable row level security;
alter table public.meal_plan_items enable row level security;

drop policy if exists profiles_owner_all on public.profiles;
create policy profiles_owner_all on public.profiles
  for all to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- Inactive ingredients remain readable so historical recipes continue to
-- calculate correctly. Ingredient pickers should filter is_active = true.
drop policy if exists ingredients_authenticated_read on public.ingredients;
create policy ingredients_authenticated_read on public.ingredients
  for select to authenticated
  using (true);

drop policy if exists recipes_owner_all on public.recipes;
create policy recipes_owner_all on public.recipes
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists recipe_ingredients_owner_all on public.recipe_ingredients;
create policy recipe_ingredients_owner_all on public.recipe_ingredients
  for all to authenticated
  using (exists (
    select 1
    from public.recipes r
    where r.id = recipe_id and r.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1
    from public.recipes r
    where r.id = recipe_id and r.user_id = (select auth.uid())
  ));

drop policy if exists meal_plans_owner_all on public.meal_plans;
create policy meal_plans_owner_all on public.meal_plans
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists meal_plan_items_owner_all on public.meal_plan_items;
create policy meal_plan_items_owner_all on public.meal_plan_items
  for all to authenticated
  using (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_id and p.user_id = (select auth.uid())
    )
    and (
      recipe_id is null
      or exists (
        select 1
        from public.recipes r
        where r.id = recipe_id and r.user_id = (select auth.uid())
      )
    )
  )
  with check (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_id and p.user_id = (select auth.uid())
    )
    and (
      recipe_id is null
      or exists (
        select 1
        from public.recipes r
        where r.id = recipe_id and r.user_id = (select auth.uid())
      )
    )
  );

-- Reset Supabase default grants before granting the application permissions.
-- In particular, TRUNCATE bypasses RLS and must never be a client privilege.
revoke all on public.profiles,
  public.ingredients,
  public.recipes,
  public.recipe_ingredients,
  public.meal_plans,
  public.meal_plan_items
from public, anon, authenticated;

revoke all on public.recipe_nutrition,
  public.meal_plan_item_nutrition,
  public.meal_plan_nutrition,
  public.meal_plan_totals,
  public.shopping_list_items
from public, anon, authenticated;

-- Trigger-only functions must not be callable through the PostgREST RPC surface.
revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.assert_recipe_has_ingredients() from public, anon, authenticated;
revoke execute on function public.assert_recipe_ingredient_parent() from public, anon, authenticated;
revoke execute on function public.validate_meal_plan_item() from public, anon, authenticated;
revoke execute on function public.validate_meal_plan_week() from public, anon, authenticated;

grant select, insert, update, delete on public.profiles to authenticated;
grant select on public.ingredients to authenticated;
grant select, insert, update, delete on public.recipes to authenticated;
grant select, insert, update, delete on public.recipe_ingredients to authenticated;
grant select, insert, update, delete on public.meal_plans to authenticated;
grant select, insert, update, delete on public.meal_plan_items to authenticated;
grant select on public.recipe_nutrition to authenticated;
grant select on public.meal_plan_item_nutrition to authenticated;
grant select on public.meal_plan_nutrition to authenticated;
grant select on public.meal_plan_totals to authenticated;
grant select on public.shopping_list_items to authenticated;
