from datetime import date
from typing import Protocol

from backend.app.domain import IngredientRecord, MealPlanRecord, ProfileRecord, RecipeRecord


class RepositoryError(Exception):
    def __init__(self, status_code: int, message: str):
        self.status_code = status_code
        self.message = message
        super().__init__(message)


class Repository(Protocol):
    def list_ingredients(self, query=None, category=None) -> list[IngredientRecord]: ...
    def get_ingredient(self, ingredient_id: int, include_inactive=False) -> IngredientRecord | None: ...
    def create_recipe(self, user_id, name, description, ingredients) -> RecipeRecord: ...
    def list_recipes(self, user_id, include_archived=False) -> list[RecipeRecord]: ...
    def get_recipe(self, recipe_id) -> RecipeRecord | None: ...
    def update_recipe(self, recipe, name, description, ingredients) -> RecipeRecord: ...
    def archive_recipe(self, recipe) -> RecipeRecord: ...
    def save_profile(self, profile: ProfileRecord) -> ProfileRecord: ...
    def get_profile(self, user_id) -> ProfileRecord | None: ...
    def create_meal_plan(self, plan: MealPlanRecord) -> MealPlanRecord: ...
    def get_meal_plan(self, user_id, week_start: date) -> MealPlanRecord | None: ...
    def add_plan_item(self, plan, item) -> MealPlanRecord: ...
    def replace_plan_items(self, plan, items, expected_revision=None) -> MealPlanRecord: ...
